### PR TITLE
Escape unicode filename while download attachment

### PR DESCRIPTION
**Pull request by bargool**
PR #384 doesn't work with apache
Got
> embedded newline in response header with name 'Content-Disposition'
From Apache

### CODE REVIEW

**Comment by benjaoming** [comment]
This makes sense given the old TODO, thanks for this!

**Comment by bargool** [comment]
As I understand from [this SO](http://stackoverflow.com/questions/1361604/how-to-encode-utf8-filename-for-http-headers-python-django) this solution works only for modern browsers (I don't have old browsers - cannot try)

**Comment by benjaoming** [comment]
Thanks @bargool for investigating, I gather that the conclusion from StackOverflow is this:

> Update: as of November 2012, all current desktop browsers support the encoding defined in RFC 6266 and RFC 5987 (Safari >= 6, IE >= 9, Chrome, Firefox, Opera, Konqueror).

**Comment by benjaoming** [comment]
...which is 2½ years ago :) So I am comfortable with this solution!

**Comment by bargool** [comment]
Thanks for quick response and merge!

**Pull request merged**
