### PR TITLE
Boostrap 4 upgrade

### PR DESCRIPTION
**Pull request by benjaoming**
Replaces #1022 by merging commits where large sources were added and removed to save git history.

@slinkymanbyday would you be interested in working more on this?

### CODE REVIEW

**Comment by benjaoming** [comment]
Still a few things missing, but it's promising to become an over-all visual improvement.

* [ ] Search input and button disconnected.
* [ ] Article menu buttons distance too small.
* [ ] Article menu perhaps too big. Wraps very early.
* [ ] Breadcrump area and adjacent dropdowns mis-aligned.

image

**Comment by benjaoming** [comment]
The responsive part also looks close to finished:

* [ ] Some spacing for the menu items missing

image

**Comment by benjaoming** [comment]
I don't like the new default bootstrap colors, so going with these as defaults instead - LMK if you prefer something else for defaults!

image

**Comment by benjaoming** [comment]
I think this is look good now - I don't spot any visual regressions, on the other hand a lot of stuff looks nicer now.

It would be nice with more visual updates and improvements:

* Please feel encouraged to add more, even small PRs with a extra padding added to some elements, all is welcome
* Perhaps we could benefit from introducing django-compressor in the `testproject`

**Comment by benjaoming** [comment]
Thanks for getting this work done @slinkymanbyday!

**Comment by slinkymanbyday** [comment]
@benjaoming colours looks good to me :)

**Pull request merged**
