### PR TITLE
Fixing CSS for details and admonition to use the theme colors.

### PR DESCRIPTION
**Pull request by orcephrye**
As per the conversation in: https://github.com/django-wiki/django-wiki/issues/1197

This brings the details/summary blocks and admonition blocks to have color parity with both each other and the Wiki color theme.

### CODE REVIEW

**Comment by orcephrye** [comment]
Two screenshots. 

First **details**/**summary** colors:
details_colors_take3

Second **admonition** colors:
admonitition_colors_take3

**Comment by oscarmcm** [comment]
Those colors looks good me!

**Comment by orcephrye** [comment]
> Those colors looks good me!

Thanks!

I have changed this from a draft into a ready to review PR.

**Review by benjaoming — APPROVED** [review]
This is a good and positive improvement!

**Review by oscarmcm — APPROVED** [review]

**Comment by oscarmcm** [comment]
Thank you @orcephrye for this!

**Pull request merged**
