### PR TITLE
User `.iter()` instead of long deprecated and removed method `.getiterator`

### LINKED ISSUE #1083: AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
Deprecated in 3.2 and removed in 3.9.

```
Internal Server Error: /wiki/
Traceback (most recent call last):
  File "$VENV/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "$VENV/lib/python3.9/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "$VENV/lib/python3.9/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "$VENV/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "$VENV/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "$VENV/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "$VENV/lib/python3.9/site-packages/classytags/core.py", line 151, in render
    return self.render_tag(context, **kwargs)
  File "$VENV/lib/python3.9/site-packages/sekizai/templatetags/sekizai_tags.py", line 87, in render_tag
    rendered_contents = nodelist.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "$VENV/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "$VENV/lib/python3.9/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "$VENV/lib/python3.9/site-packages/wiki/templatetags/wiki_tags.py", line 53, in wiki_render
    content = article.get_cached_content(user=context.get("user"))
  File "$VENV/lib/python3.9/site-packages/wiki/models/article.py", line 250, in get_cached_content
    cached_content = self.render(user=user)
  File "$VENV/lib/python3.9/site-packages/wiki/models/article.py", line 211, in render
    article_markdown(
  File "$VENV/lib/python3.9/site-packages/wiki/core/markdown/__init__.py", line 49, in article_markdown
    return md.convert(text)
  File "$VENV/lib/python3.9/site-packages/wiki/core/markdown/__init__.py", line 31, in convert
    html = super().convert(text, *args, **kwargs)
  File "$VENV/lib/python3.9/site-packages/markdown/core.py", line 267, in convert
    newRoot = treeprocessor.run(root)
  File "$VENV/lib/python3.9/site-packages/wiki/core/markdown/mdx/responsivetable.py", line 15, in run
    for table_wrapper in list(root.getiterator("table")):
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
```

### PR DESCRIPTION
**Pull request by benjaoming**
Fixes #1083 

Thanks @teury for finding the solution!

### CODE REVIEW

**Comment by HugoDelval** [comment]
Thanks for the fix! I would be really interested in a release including this fix, do you have an idea how long it takes in general to make a release?

Thanks a lot for the great project!

**Comment by benjaoming** [comment]
@HugoDelval - thanks for asking and signalling the importance of this - making a note to self to release this within the week :)

**Comment by benjaoming** [comment]
This is now released @HugoDelval :)

**Comment by HugoDelval** [comment]
Thanks a lot :tada:

**Pull request merged**
