### PR TITLE
Python markdown 34 support

### PR DESCRIPTION
**Pull request by orcephrye**
As per:
Discussion:  https://github.com/django-wiki/django-wiki/discussions/1312
Issue: https://github.com/django-wiki/django-wiki/issues/1197
Issue: https://github.com/django-wiki/django-wiki/pull/1274

This updates the Wiki requirements to Markdown 3.4.4

All tests pass on Python 3.8. I need to configure Hatch to see 3.9 and 3.10 (I am skipping 3.7 as it is deprecated). 

I also have yet to run the tests with Selenium, but I have experience in that just haven't yet. 

Appreciate any help and advice to see this PR through.

### CODE REVIEW

**Comment by orcephrye** [comment]
So I have run test:all with 3.8/9/10 environments configured as also with Selenium enabled. 

All the non-Selenium tests are passing. But 1 Selenium test is failing. 
`========================================================================================== short test summary info ===========================================================================================
FAILED tests/core/test_views.py::EditViewTestsSelenium::test_preview_and_save - selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
`

However, I ran that again in the main branch  (I did 'hatch run test:clean' and 'hatch run clean-pyc' after checkout just to be safe) and still getting the error... not sure but it looks like this may not be Markdown's fault?   


All in all I am feeling pretty good about this now that I have ran it against other versions.

**Comment by orcephrye** [comment]
Side note: It looks like hatch test environments are not respecting the Django version requirement!?

```
(wiki) (django-wiki-dev) rye@localhost:~/PycharmProjects/django-wiki> hatch run test.py3.9-dj2.2:test
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.9.18, pytest-6.2.5, py-1.11.0, pluggy-1.3.0
django: settings: tests.settings (from ini)
rootdir: /home/rye/PycharmProjects/django-wiki, configfile: pyproject.toml, testpaths: tests
plugins: pythonpath-0.7.4, django-4.5.2, cov-4.1.0, django-webtest-1.9.11
collected 275 items
```

Or am I doing something wrong?

**Comment by oscarmcm** [comment]
I think that comes from the Django plugin for pytest

https://github.com/django-wiki/django-wiki/blob/main/pyproject.toml#L102

**Comment by oscarmcm** [comment]
Hey, everything here looks good! 

Gonna keep testing this a bit more :)

**Comment by orcephrye** [comment]
According to this: https://python-markdown.github.io/extensions/toc/#usage

TOC has added the "toc_class" parameter which looks like it takes a list. Not sure how that is going to work with the current regex?

I will have to test that at some point soon.

**Comment by benjaoming** [comment]
There's also a Markdown 3.5 available now. It seems like it doesn't contain breaking changes.

**Comment by orcephrye** [comment]
Should we close this PR and skip 3.4.4  or perhaps just merge this and then make a new PR for 3.5?

**Comment by oscarmcm** [comment]
I think we should keep this open, then merge once its stable and later on bump to 3.5

**Comment by orcephrye** [comment]
I just updated the branch to include a test of the 'toc_class' argument which is new as of 3.4. It appears to work fine. 

Everything seems good on my end.

**Comment by oscarmcm** [comment]
Cool, I'll take the final look and then merge this!

Thanks for the hard work here @orcephrye

**Comment by oscarmcm** [comment]
Thanks for all the work here @orcephrye

**Pull request merged**
