### PR TITLE
migrations: Fix incorrect table names and remove redundant tables

### PR DESCRIPTION
**Pull request by tbabej**

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks for looking into this. I'm just wondering why you have these table names. Look for instance at the tables created in `0001_initial` :

https://github.com/django-wiki/django-wiki/blob/releases/0.0.24/wiki/plugins/images/south_migrations/0001_initial.py

The same was the case in 0.23:

https://github.com/django-wiki/django-wiki/blob/alpha/0.0.23/wiki/plugins/images/migrations/0001_initial.py

In both 0.23 and 0.24, the table was called images_image (or `attachments_attachment`), that should be consistent with the current renaming. I'm wondering why you have a table called `wiki_image`.. would you know the origin of that name?

**Comment by tbabej** [comment]
@benjaoming See my investigation results I spammed into #430 . It seems that even in the demo that is shipped in git with alpha/0.0.23 release tag, the wiki_* tables are there, and data is saved in those tables instead.

Do not take my word, try it :)

**Comment by benjaoming** [comment]
@tbabej 

Would you be able to make a change before merging? Since this issue is supposed to be released as a fix for the future, could we do the following?

For people upgrading from a 0.24.* version: We have an extra migration: 0004_label_v01_rename_fix.py -- it checks if `wiki_image` etc. still exist: If they do, it does the rename and removes the table. This will NOT trigger if the fix `0003_label_v01_rename.py` has been run but only triggers in case the previous version of `0003_label_v01_rename.py` was run.

**Comment by tbabej** [comment]
Sure, however, probably no sooner than during the weekend.

**Comment by benjaoming** [comment]
I'm sure you've understandably left this long ago :) But there is a problem that migrations don't run from scratch on postgres:

```
FATAL ERROR - The following SQL query failed: ALTER TABLE "wiki_articlesubscription" RENAME TO "wiki_notifications_articlesubscription";
The error was: relation "wiki_articlesubscription" does not exist

Error in migration: notifications:0004_label_v01_rename
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "wiki/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "wiki/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "wiki/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "wiki/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "wiki/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "wiki/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "wiki/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "wiki/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "wiki/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "wiki/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "wiki/local/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "wiki/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/media/archive/code/django-wiki/testproject/wiki/plugins/notifications/south_migrations/0004_label_v01_rename.py", line 13, in forwards
    db.rename_table("wiki_articlesubscription", "wiki_notifications_articlesubscription")
  File "wiki/local/lib/python2.7/site-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "wiki/local/lib/python2.7/site-packages/south/db/postgresql_psycopg2.py", line 48, in rename_table
    generic.DatabaseOperations.rename_table(self, old_table_name, table_name)
  File "wiki/local/lib/python2.7/site-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "wiki/local/lib/python2.7/site-packages/south/db/generic.py", line 375, in rename_table
    self.execute(self.rename_table_sql % params)
  File "wiki/local/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "wiki/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "wiki/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "wiki/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "wiki/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "wiki_articlesubscription" does not exist
```

I'll have a look at it now and see what can be done, then merge and make another final 0.0.24 release :)

**Comment by benjaoming** [comment]
I can now create a clean install of 0.0.23, and then migrate it to 0.0.24... and then to current master (0.1).

I found issues running postgres regarding transaction management which are committed to the releases/0.0.24 branch.

**Pull request closed without merging**
