### PR TITLE
Styling fix for code blocks with line numbers

### PR DESCRIPTION
**Pull request by azaghal**
As of current master, code blocks with line numbers (with Pygments library installed) end-up looking different compared to plain code blocks. In addition to standing out styling-wise, they also break the responsiveness of the pages by overflowing outside of visible viewport when screen is too small.

Don't hesitate to ask for improvement to the pull request, since I am not really a master of CSS.

### CODE REVIEW

**Comment by azaghal** [comment]
Hm, forgot to reference a relevant issue, but basically this would fix issue #601.

**Comment by benjaoming** [comment]
@azaghal great! do you need any additional verification or does it _just work_? :)

**Comment by azaghal** [comment]
Well, works for me (tm), but would be good if you checked locally as well. And as long as the CSS looks fine to you :)

**Comment by benjaoming** [comment]
Working nicely in FF 52 and Chromium :)

screenshot from 2017-04-06 13-54-34

**Pull request merged**
