### PR TITLE
Fix double escaping of block code

### PR DESCRIPTION
**Pull request by Benbb96**
I faced same issue as https://github.com/django-wiki/django-wiki/issues/945 and I was wondering why its was not merged so I made a Pull Request inspired by these piece of codes : https://github.com/Python-Markdown/markdown/pull/727 and https://github.com/jenda1/django-wiki/commit/07ea6d3360cd54cbbebc5291d34d58c5f3e8453f

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks this is indeed a confirmed bug and you found a really good reference for the fix :+1:

**Comment by Benbb96** [comment]
Thank you very much for the quick merge and deploy to PyPi !

**Comment by benjaoming** [comment]
You're welcome, was super-glad to see someone finally fix this :tada:

**Comment by benjaoming** [comment]
The bug has been "live" on the demo page for a very long time, but it now shows correctly :) https://demo.django-wiki.org/#wiki-toc-code-blocks

**Pull request merged**
