### PR TITLE
Typo and missing import in installation instructions.

### PR DESCRIPTION
**Pull request by Russell-Jones**
Tested with Django 1.8 + Python 3.4.2

### CODE REVIEW

**Comment by benjaoming** [comment]
Oh thanks, I guess the intention of the urls.py thing was to ne a copy-paste snippet:

    urlpatterns += patterns

It won't work without having a previously defined `urlpatterns` anyways..

Should we instead make a fully working urls.py?

**Comment by Russell-Jones** [comment]
I was thinking it'd add as a mnemonic to add the import to the default url.py (it's needed in the one for 1.8 at least) rather than people cutting and pasting, getting an error, puzzling over where to import from, then adding the import, which is how it went for me.

**Comment by benjaoming** [comment]
Doesn't Django 1.8 actually raise deprecation warnings if you use the `pattern()` construct?

**Comment by benjaoming** [comment]
Agreeing with the change of course :) Let's address the issue about patterns() later, it would also be erroneous to have a documentation that doesn't work for django 1.6 while it's officially supported.

**Comment by Russell-Jones** [comment]
Hi, would have replied earlier if I'd not needed to restore from backup after HDD failure :)
I guess it can be updated when 1.6 drops out of support in distros, or it can be updated to use try/except for the newer form (though I don't know what that would be, TBH).

**Comment by benjaoming** [comment]
Welcome back :)

I think we can leave this until 1.6 is dropped, probably won't be long...

**Pull request merged**
