### PR TITLE
Simplified wiki.core.utils.object_to_json_response.

### PR DESCRIPTION
**Pull request by atombrella**
Probably more tests around this should be added.

### CODE REVIEW

**Comment by atombrella** [comment]
Probably more tests around this should be added.

**Comment by benjaoming** [comment]
So the current `master` targets only Django 1.11 and Django 2.0.

So you are welcome to make a change in tox.ini, removing Django 1.8 to allow for this change to happen.

**Comment by benjaoming** [comment]
Ref: http://django-wiki.readthedocs.io/en/master/release_notes.html#release-plan

**Comment by benjaoming** [comment]
Oh you enjoyed that :P

**Comment by benjaoming** [comment]
Alright, so `master` is now officially only Python 3.4+ and Django 1.11+

I guess we can look at the coverage report above and it will identify some of the areas that have gone stale after this change..

image

**Pull request merged**
