### PR TITLE
Better Chinese Locale

### PR DESCRIPTION
**Pull request by trychen**
Added Traditional Chinese and supplemented the Simplified Chinese local message

### CODE REVIEW

**Comment by benjaoming** [comment]
Sounds great! Did you by any chance pull changes from Transifex first? And did you implement them there, too? Otherwise, it just requires some manual stuff using the `tx` client...

**Comment by trychen** [comment]
not yet. i have requested to join the Chinese (China) language translation of the django-wiki project just now.

**Comment by benjaoming** [comment]
Do you have access with Transifex to upload your work or should I try to merge this and get it uploaded?

**Comment by benjaoming** [comment]
Ping @trychen :)

**Comment by benjaoming** [comment]
It looks like you've been active on Transifex - I'm assuming it's you and that we can close the PR. I'll pull in all language changes so it's in the master.

Thanks for contributing!

**Pull request closed without merging**
