### PR TITLE
Use methods from markdown.extensions.toc

### PR DESCRIPTION
**Pull request by atombrella**
This module can be simplified more.

### CODE REVIEW

**Comment by benjaoming** [comment]
I recall that the reason why this module looks as it does, is because changes have been done in those functions -- they aren't supposedly raw copies?

See:

https://github.com/atombrella/django-wiki/commit/d3b0417acf8599625e7a196d1e65b62c42436015

**Comment by benjaoming** [comment]
I don't think this change is desirable, unless you wanna investigate the various versions of the Markdown dependency..

**Comment by atombrella** [comment]
@benjaoming The replaced functions are raw copies. Your comment in the top indicates that this extension could be simplified. We can close it, I don't want to break things.

**Comment by benjaoming** [comment]
@atombrella I updated my comment - no, they don't seem to be modified, it's because they are removed in subsequent Markdown releases.

**Pull request closed without merging**
