### PR TITLE
Adds a functional test for the TOC plugin

### PR DESCRIPTION
**Pull request by benwah**
Just adding a test for TOC. I think the TOC codepath is already executed in some of the tests, but this adds a TOC-specific content assertion.

I want to add a horizontal TOC markdown plugin so I need to starts with some basic tests.

ping @benjaoming

### CODE REVIEW

**Comment by benwah** [comment]
Oh actually it adds to coverage - nice

**Comment by benwah** [comment]
* fixed typo in test name

**Comment by benjaoming** [comment]
This is surely needed! Thanks for adding!

Would you mind creating a `tests/` package in `wiki/plugins/macros` and having it sit there as `test_toc.py`? Because that would make it the start of some much needed tests for the `macros` plugin where `toc` lives..

**Comment by benwah** [comment]
Sure @benjaoming I'll try to get to it tonight.

**Comment by benjaoming** [comment]
Will refactor tests at a later occasion - think we should move everything to a separate `/tests/` structure as most projects do nowadays..

**Comment by benjaoming** [comment]
Thanks for having such impact on test coverage @benwah ! :)

**Comment by benwah** [comment]
Sounds good - I'll spin by #django-wiki on IRC at some point so we can chat how to structure tests.

**Pull request merged**
