### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by atombrella**

### CODE REVIEW

**Comment by atombrella** [comment]
@benjaoming You can have a second look. Notice that on different setups, the code coverage increased to 70% :D

**Comment by benjaoming** [comment]
@atombrella great work! I don't know where the Codecov.io metrics went, apparently they have a new Github App Integration. I've just activated it - could you re-apply the latest commit and do a force push? Should prompt a Travis build, which should then prompt Codecov.io to do its job :)

**Comment by atombrella** [comment]
@benjaoming Doesn't seem to be working. I pushed some more clean-ups.

**Comment by benjaoming** [comment]
Looks like we aren't generating a coverage report anymore:

```
[0;90m==>[0m Travis CI detected.
    [0;90mproject root:[0m .
    [0;32mYaml not found, that's ok! Learn more at[0m [0;36mhttp://docs.codecov.io/docs/codecov-yaml[0m
[0;90m==>[0m Running gcov in . [0;90m(disable via -X gcov)[0m
[0;90m==>[0m Python coveragepy not found
[0;90m==>[0m Searching for coverage reports in:
    [0;32m+[0m .
[0;31m-->[0m No coverage report found.
    Please visit [0;36mhttp://docs.codecov.io/docs/supported-languages[0m
```

**Comment by benjaoming** [comment]
Am looking into missing coverage in #706 ... seems like the coverage report is there, but codecov isn't sending it...

**Comment by benjaoming** [comment]
This is an excellent PR, says a lot about the pile-up of compatibility-related issues over time. Thanks for keeping this project alive and well!

**Pull request merged**
