### PR TITLE
Use a pure python script for artifact build

### PR DESCRIPTION
**Pull request by oscarmcm**
Discussed on:
- #1366

Attempt to fix:

- #1367

Likely related to:
- #1369

### CODE REVIEW

**Comment by oscarmcm** [comment]
@Dev-Mehta Please check when you get a chance :)

And sorry for the delay on this, life and work has been harder recently.

**Comment by oscarmcm** [comment]
Docs are passing correctly

https://django-wiki--1370.org.readthedocs.build/en/1370/

**Comment by oscarmcm** [comment]
Tests are passing correctly

https://app.circleci.com/pipelines/github/django-wiki/django-wiki/559/workflows/6f0ca603-3176-45f3-a50c-7f5a7a3ccb86/jobs/8019

**Review by Dev-Mehta — APPROVED** [review]
Hey @oscarmcm, No worries at all! I’ve checked the changes, and everything looks good on my end. The script works as intended now and fixes the issues discussed in #1367.

**Comment by oscarmcm** [comment]
@benjaoming are we going to create a new release ?

**Comment by benjaoming** [comment]
@oscarmcm great work! gonna have a look soon, but supposing it works.

> @benjaoming are we going to create a new release ?

does this require a new release? isn't it purely fixing issues in the development setup?

**Comment by oscarmcm** [comment]
Naw, it’s not required. Once you review it, pls just merge it :)

**Review by benjaoming — APPROVED** [review]
Nice with the new friendly failure messages for when pysassc is missing :100:

**Pull request merged**
