### PR TITLE
Patch for image markdown

### PR DESCRIPTION
**Pull request by inflrscns**
Fixes images inside tables so they arent displayed in a new row. Images that were inserted besides text on a single line no longer appear after the text, the text will now wrap around the image.

Edit: Forgot to mention, this patch is in regards to [this issue.](https://github.com/django-wiki/django-wiki/issues/204)

## Test markdown:
test markdown  
<br/>
## How it renders before:
before  
<br/>
## And after:
after

### CODE REVIEW

**Comment by benjaoming** [comment]
Hi @inflrscns !

Thanks for this fix! And thanks for the nice image proofs. Would you be able to screenshot the changes regarding:

 * Images with captions
 * Images that are not inline
 * Images with captions in tables

In case errors are same as before, it's not that I mind merging, we can put such problems in a separate issue.

Regards

**Comment by inflrscns** [comment]
Hello @benjaoming,

Here are some additional screenshots. Let me know if you need any more, or if I missed something. I'm happy to supply them!

### Test Markup
test markup

### Results
results

PS: Speaking of separate issues, I noticed that thumbnail \<div>'s are wrapped in \<p> tags, which is not valid html. Do you think I should open an issue for this?

**Comment by benjaoming** [comment]
> PS: Speaking of separate issues, I noticed that thumbnail <div>'s are wrapped in <p> tags, which is not valid html. Do you think I should open an issue for this?

Yes - please do! I have a feeling, though, that the culprit is Markdown adding the `<p>` tags by default to what it considers paragraphs... but it's probably fixable.

**Comment by benjaoming** [comment]
It looks like the patch works well!! :+1:

**Comment by inflrscns** [comment]
Thank you!! :)

**Pull request merged**
