### PR TITLE
Refactor code for issue #1129

### PR DESCRIPTION
**Pull request by iqbalabd**
I've tried refactoring the repetitive code and reverted the code before #1099

### CODE REVIEW

**Review by benjaoming — APPROVED** [review]
This is looking good :+1: Perhaps expanding the docstring could be helpful for future developers. And then there was some linting stuff, try to run `tox -e lint` locally to reproduce?

**Comment by benjaoming** [comment]
Thanks for addressing my feedback!!

Can you see this page? https://app.circleci.com/pipelines/github/django-wiki/django-wiki/68/workflows/eac8194b-d2cb-4bb4-b10f-cbc96700ce98/jobs/694 (I'm unsure if there's some issue with other folks having access)

If not, the linting issues are these 2:

image

**Comment by iqbalabd** [comment]
@benjaoming Thank you for looking at this and approving. I can access the CircleCI page.

I've tried to fix the linting issues as much as possible but there is still one more test which is not passing and I have run out of ideas on why this is an issue, so I will leave this as it is.

**Comment by benjaoming** [comment]
That's understandable -- the last failing test is a very marginal slip in over-all test coverage. This can happen when duplicate (but tested) code is written in a shorter way. But it's no problem here.

**Comment by benjaoming** [comment]
The way to fix it would be to add a unit test of `add_to_registry` that tests all the possible input values. But I think it's low priority.

**Comment by benjaoming** [comment]
Thanks for the contribution!

**Comment by iqbalabd** [comment]
Thank you @benjaoming !

**Pull request merged**
