### PR TITLE
Adds Django 3.1 support, drops Django 2.1

### LINKED ISSUE #1056: Remove Django 2.1 support
CC: @atombrella

### PR DESCRIPTION
**Pull request by atombrella**
https://docs.djangoproject.com/en/3.0/releases/3.0/#id3

Fixes #1056

### CODE REVIEW

**Comment by benjaoming** [comment]
Any idea why this isn't building on Travis? https://travis-ci.org/github/django-wiki/django-wiki

**Comment by atombrella** [comment]
No. I was wondering the same thing.

**Comment by benjaoming** [comment]
I can see that Github calls the Notification API in Travis' end and receives a non-error response 204.

image

**Comment by benjaoming** [comment]
After the migration to travis-ci.com, the latest PR is building. It took some time before it was in effect. Perhaps if you do a `git commit --amend` and force-push, this PR will also get picked up by Travis?

**Comment by atombrella** [comment]
There was a syntax error (typo with a colon) in the `.travis.yml` that I didn't notice before now :/ Anyway, it's building :+1:

**Comment by benjaoming** [comment]
Hi @atombrella - is there a cunning way to pin 3.1 so it keeps working when 3.1 (final) is released? Currently it fails because pre-releases arent captured by `django>=3.1`, so it doesn't resolve.

**Comment by atombrella** [comment]
3.1 was just released yesterday :+1: I force-pushed and triggered Travis again.

**Comment by benjaoming** [comment]
Thanks @atombrella - this looks great :+1: 

There are 2 more places to fix - setup.py and README.rst -- I can have a look asap.

**Comment by atombrella** [comment]
@benjaoming :+1: I'm in doubt about `README.rst` because 0.6 seems to have been released (or is in beta), so maybe a new row should be added with `0.7 (DEV)`?

**Comment by benjaoming** [comment]
@atombrella ah yes we shouldn't drop 2.1 support in a patch release, that's true!

**Review by benjaoming — APPROVED** [review]
Targeted master to 0.7.dev, so I think this looks good now :+1: Thanks @atombrella :)

**Pull request merged**
