### PR TITLE
Bleach after markdown processing + First initial whitelist of tags and attributes

### PR DESCRIPTION
**Pull request by benjaoming**
This is an attempt of fixing #596.

I've tried with Pygments, and it works with the previous odd display of linenumbers still showing up. Should probably test some more in regards to syntax highlighting.

Also needs testing in relation to attachments.

### CODE REVIEW

**Comment by benjaoming** [comment]
Working on the Pygments highlighting as well, now appears like this @azaghal 

The scrolling, however, does not show up at least in my Firefox test. I think the `overflow: auto/scroll` CSS property doesn't trigger on tables.

screenshot from 2017-02-15 01-00-45

**Comment by azaghal** [comment]
No, that overflow setting does not apply on tables. Did some in-browser to get it working, but it looks like either the display property of tables has to be messed with, or table has to be wrapped in a `<div>` (and then you set-up the div for scrollbar). It could be this kind of fix would be needed on python-markdown side, though.

**Comment by azaghal** [comment]
Hm... I do believe the thing would need changes in python-markdown for the additional div wrapper around table - possibly somewhere in `codehilite.py:123`, or even better there should be combination of changes in pygments (specify additional wrapper around table) + python-markdown (expose the option from pygments).

**Comment by azaghal** [comment]
Hm... I do believe the thing would need changes in python-markdown for the additional div wrapper around table - possibly somewhere in `codehilite.py:123`, or even better there should be combination of changes in pygments (specify additional wrapper around table) + python-markdown (expose the option from pygments).

**Comment by benjaoming** [comment]
This is how code highlighting looks after the changes:

screenshot from 2017-02-19 17-50-39

**Comment by benjaoming** [comment]
Merging this after positive feedback from @nickfsolly

**Pull request merged**
