### PR TITLE
Pymdown blocks support

### PR DESCRIPTION
**Pull request by orcephrye**
This is for Issue: #1197 

I need help! 

There are several things that are not complete about this PR. However, it is working and it is a start and I figured I could use this as a way to get help.

1) I am not a CSS person so there are questions around how to get these different blocks to look correct. Particularly with detail/summary tags. I also wanted to use font awesome icons but I couldn't get that to work for some reason. 

2) Currently, the sidebar for the markdown editor only supports macros and seems to exist only within the macros plugin. But it makes sense that PyMdown extensions should show up in that sidebar right? However, I am unsure as to how to proceed with that. 

There may be more things to discuss but this is a starting place.

### CODE REVIEW

**Comment by orcephrye** [comment]
Also I don't know why these tests are failing. Running >hatch run test:all had all passing. I will take another look. But these tests have been problematic as of late.

**Comment by orcephrye** [comment]
> Also I don't know why these tests are failing. Running >hatch run test:all had all passing. I will take another look. But these tests have been problematic as of late.

I fixed it. It was a caused bunch some merges that screwed up the pyproject.toml file. The version I had no longer had the pymdown-extension dependency but the package was still installed in my test environments. So it was working for me but failing here.

**Comment by oscarmcm** [comment]
Thanks for the PR @orcephrye I'll take a look on this.

Im just worried by the codecov decrease.

**Comment by orcephrye** [comment]
> Thanks for the PR @orcephrye I'll take a look on this.
> 
> Im just worried by the codecov decrease.

I am extremely confused by this and thus a little worried too. So the 72.72% is from the diff not the whole project.  It looks... sorta like it is complaining that I am not testing the apps.py file? But the apps.py is just a simple little configuration. I can add a 'test' for it but it feels pointless and stupid.

**Comment by oscarmcm** [comment]
yeah, I think the same too.

Let me see what I can do, maybe tell `codecov` to not read that file will help us

**Comment by oscarmcm** [comment]
Thanks for the help with this @orcephrye 🎉

**Comment by orcephrye** [comment]
> Thanks for the help with this @orcephrye 🎉

Hey... I felt like this PR wasn't finished. Sorry for any confusion. Perhaps I should have just linked to a branch and kept talking about Blocks in the Issue instead. But I do not feel that this is a finished solution. It works. If the plugins are enabled then the PyMarkdown blocks (minus Tab) will work. 

However, I have questions about the styling/CSS for the blocks. IE: Does the color fit? Should Icons for the different types be a good idea? How can I use the icons that are already setup in scss? I tried and couldn't figure out how to use them.

Also, I think we should add documentation to the Marco sidebar so that someone who has this plugin enabled can see how to take advantage of it. The problem is that currently that is located within the marcos plugin. Not sure the best way to go about adding to that.

**Comment by benjaoming** [comment]
Good that you mention it @orcephrye - I had the impression that it wasn't finished because of your comment in the PR description, and I originally wanted to have tested it out manually to understand layout issues.

But it's always nice to get things merged :) You can use the "draft" state for the PRs to ensure that there's full clarity about the state of the work. I sometimes also add "WIP" to the PR title to make sure it's really really clear :joy:

**Comment by benjaoming** [comment]
But now harm done here, seems the additional improvements can come in follow-up PRs :+1:

**Pull request merged**
