### PR TITLE
Fix errors in import script

### PR DESCRIPTION
**Pull request by the-glu**
This fix multiples issues in the import script for mediawiki:

* `only_printable` was broken
* Switch from `%` to `format` syntax
* Fix unicode issues with `u""` (and `format`)

### CODE REVIEW

**Comment by cXhristian** [comment]
No need to use u'' when `unicode_literals` is imported.

**Comment by the-glu** [comment]
Fixed :)

**Comment by benjaoming** [comment]
Nice, thanks for modernizing the code as well! Out of interest, how did your mediawiki import go?

**Comment by the-glu** [comment]
Seems to be ok, we're checking now before removing mediawiki ^^

**Pull request merged**
