### PR TITLE
Bootstrap4

### PR DESCRIPTION
**Pull request by slinkymanbyday**
Work towards closing off https://github.com/django-wiki/django-wiki/issues/518

There are probably some tiny things i missed however this PR should cover most things (I used the testproject to make sure that most things have remain unchanged). The biggest difference is probably font size and spacings, which can be tweaked.
I don't think it looks quite as polished as the current bootstrap 3 version, but it's not far off in my opinion.

- Select2 is used in favour of typeahead, since typeahead appears to be abandoned and doesn't play well with bootstrap4.
- jQuery-ui has been removed (also a bit of a dead project). This means the resizing of modals has been removed, but I think I've made that OK with some dynamic resizing according to window size.
- Font-awesome was updated to latest, since bootstrap4 uses scss and I had to make changes here for that anyway
- jQuery updated to latest

### CODE REVIEW

**Comment by benjaoming** [comment]
Hi @slinkymanbyday 

I suppose this took a lot of work? Can you introduce the changes made?

I remember mainly that it's things like the editing area, the preview modals, and history page that complicated the upgrade.

**Comment by slinkymanbyday** [comment]
@benjaoming 
A summary of the changes:

- panel-* classes was no longer available, replaced by card-*
- pull-* classes was replaced by float-*
- I was unable to get typeahead.js working well with how bootstrap4 did form inputs, so i switched to select2
- form modal sizing was not being calculated properly with jQuery resize, so i removed that and changed how big the modal is on launch (and made it responsive). This means that modals can no longer be resized. This also removes jQuery-UI
- Bootstrap 4 uses Sass not Less for compiling CSS, so I did the changes to make this work (also migrating to font-awesome Sass instead off Less)
- Due to above, icons have been updated to work with newest font-awesome
- Dropdowns are done a bit differeently than before, so dropdowns were redone in the correct bootstrap4 way
- pre elements were no longer highlighted by default, so included a new "#article-container pre " style to highlight pre elements
- The following were updated to work with newest bootstrap way of doing things:
   - nav items 
   - dropdowns (doesn't use lists anymore, but divs/spans instead)

Looking now I do have a couple fixes to make before this can be merged. I think I messed up something in the modal sizing before I made the commit. Will fix up and report back

**Comment by slinkymanbyday** [comment]
@benjaoming 
Have commit the fixes i mentioned in my previous comment around modal sizing, it should now be what I intended in the first place.

**Comment by benjaoming** [comment]
THANKS! That's a really helpful list.

I'll have a look at your branch very soon, I'm wondering if the current `master` should be released before this.

**Comment by slinkymanbyday** [comment]
I think it would be good for master to release before this (which would include django3 support).
Bootstrap 4 upgrade is likely to break custom plug-in styling so might be good to release before this gets merged.

**Comment by benjaoming** [comment]
I'll let this PR simmer and focus on an 0.6 release

We can of course also have release branches, such that both 0.6 and an upcoming 0.7 are supported.

**Comment by slinkymanbyday** [comment]
@benjaoming 
what else is needed for 0.6 release? would love to help get it over the line.

**Comment by benjaoming** [comment]
@slinkymanbyday I released 0.6b1 yesterday, it seems to work, so I guess I'll bump it as a stable release soon.

**Comment by benjaoming** [comment]
Hi @slinkymanbyday - there are a lot of files being added and deleted again in the commits, I will try to create a branch from yours and edit your commits to not include all the bootstrap source files.

**Comment by benjaoming** [comment]
Also, big time sorry for not having a look at this before now!

**Comment by benjaoming** [comment]
Curious: Have you been running this in production, and how has that been going? Is it fully baked? There are many changes in doing these Bootstrap upgrades, been doing them a couple of times.. still finding stuff months after.

**Comment by slinkymanbyday** [comment]
Have not been running in production yet. 
was waiting to have bootstrap 4 sorted out so I can work on #1023 before putting it into production.
happy to work on #1035 some more in the next few days (should have some time)

**Comment by benjaoming** [comment]
Great idea to solve #1023 ! I made a few more improvements in #1035 - but I sense that there's a lot of little visual breakage that have to be discovered by a keen eye, so will take a bit of time to iron out.

**Comment by benjaoming** [comment]
I would like #1035 to be "tolerable" for a release before merging it.. feeling like it's a bit dangerous to have unfinished work in `master`.

**Comment by benjaoming** [comment]
Closing this one, please send PRs to my branch: https://github.com/benjaoming/django-wiki/tree/boostrap4

**Pull request closed without merging**
