### PR TITLE
Allow django-mptt > 0.7.1 as a dependency

### PR DESCRIPTION
**Pull request by spookylukey**

### CODE REVIEW

**Comment by benjaoming** [comment]
Maybe django-mptt<0.8 ?

It's been breaking a lot :/

**Comment by spookylukey** [comment]
Ah. Normally I would be optimistic and leave it open-ended - to me, "django-mptt<0.8" means "I know this doesn't work with 0.8". If people discover a problem with a specific mptt version they can always avoid that by choosing carefully, but if you've over-specified the version then you've potentially caused them a bigger problem.

I'm happy to change it to what you think though.

**Comment by benjaoming** [comment]
I think it's fine to put upper limits.

I've had lots of problems deploying old projects with django-cms and django-blog-zinnia because if missing upper limits.

For django-mptt, the suspicion is based on experience :)

**Comment by benjaoming** [comment]
**) I also had problems with these projects, because they didn't have an archived pip freeze of their virtualenvs.

**Comment by spookylukey** [comment]
Updated as per suggestion now.

**Comment by benjaoming** [comment]
Grrr8! Merging!

**Comment by benjaoming** [comment]
Thanks and have a nice day :)

**Pull request merged**
