### PR TITLE
Tests for article model

### PR DESCRIPTION
**Pull request by Alkalit**
@benjaoming what do you think?

I also have are few questions:
1 URLPath looks tricky for me. Maybe simply mock this test (mean no library, just monkey patching)?
2 What does "NB" in Article methods doc's mean (I dont have formal CS degree)?

### CODE REVIEW

**Comment by benjaoming** [comment]
*NB!* is not a CS degreen thing... more an old-school English thing :)

> Nota bene (/ˈnoʊtɑːˈbɛnɛ/; plural form notate bene) is an Italian and Latin phrase meaning "note well". The phrase first appeared in writing circa 1721.

But just means "take care".

URLPath, I would suggest creating a tree structure in the test and see that paths are generated and resolved correctly? At first grasp, I don't think it needs mocking, but have you encountered any issues?

**Comment by benjaoming** [comment]
Btw thanks again!!

**Comment by benjaoming** [comment]
Great test structure again!

The `test_get_absolute_url_if_urlpath_set_is_not_exists` test expects an article to be in '/1/', which would assume that the wiki urlconf is installed at the root level. Which could be the case, however it will not always hold.

It would be interesting (maybe more for the URLPath tests) with a test that ensures that URLs are correct both when the wiki is running from '/' and '/my-wiki/' :)

Will merge no matter what, just flinging in an idea :+1:

**Comment by Alkalit** [comment]
I know what does Nota Bene means. Just do not expected to see it in the docs. I thought it had something related to databases and data structures.

No issues. Just trying to figure out how it works.

Ok, will check this, too.

**Comment by Alkalit** [comment]
I got another issue. When I run testcases separatly, (say wiki.tests.test_models.ArticleModelTest.test_get_absolute_url_if_urlpath_set_is_exists__no_root_urlconf) tests passes. But when I try launch them all at once, I getting error. It looks like isolation issue again.

**Comment by benjaoming** [comment]
Thanks for this! I'm looking into merging it.

I think the problem may have to do with the way that the urlconf is loaded using `wiki.urls.get_pattern()`, maybe it's only called once before the tests run... that's what I gather from debugging it now.

**Comment by benjaoming** [comment]
I tried forcing a reload of the urlconf but with no success, because the already loaded module has been injected elsewhere and URLs will be loaded from `reverse()` using the already loaded urlconf.

**Pull request merged**
