### PR TITLE
Fully specify custom group models for tests 

### PR DESCRIPTION
**Pull request by benjaoming**
Fixes part of the problem described in #801

Just as a boiled down copy of Django's implementation!

CC: @azaghal

### CODE REVIEW

**Comment by benjaoming** [comment]
@azaghal I concede that this is a bit of a mess -- and it seems that the custom user model has to customized further to actually be pointing at the custom groups.

Firstly, extending Django's original group permission system requires copy-pasting. Secondly, `Group` not a swappable model, neither is `Permission` -- so aspects of `AbstractUser` (or maybe it's `PermissionMixin`) that mention it, have to be redefined in the custom user model.

**Comment by benjaoming** [comment]
ping @azaghal - would you be able to see if this implementation of a custom group model is sufficient for the tests that you mentioned which couldn't run with the previous limited model?

**Comment by azaghal** [comment]
I'll have a look, got a bit busy :)

**Comment by azaghal** [comment]
No, I don't think it's sufficient to help.

Here's a quick and dirty test that would need to pass (had something more complex in place, but this should demo the issue). If you comment-out the `WIKI_GROUP_MODEL = 'testdata.CustomGroup'` line in `tests/settings.py`, the test should pass.

```
diff --git a/tests/core/test_views.py b/tests/core/test_views.py
index 60b9eabf..19adb476 100644
--- a/tests/core/test_views.py
+++ b/tests/core/test_views.py
@@ -513,6 +513,34 @@ class DeletedListViewTest(RequireRootArticleMixin, ArticleWebTestUtils, DjangoCl
         response = self.client.get(resolve_url('wiki:deleted_list'))
         self.assertContains(response, 'Delete Me')
 
+    def test_redirect_non_superuser_to_root(self):
+        response = self.client.post(
+            resolve_url('wiki:create', path=''),
+            {'title': 'Delete Me', 'slug': 'deleteme', 'content': 'delete me please!'}
+        )
+
+        response = self.client.post(
+            resolve_url('wiki:delete', path='deleteme/'),
+            {'confirm': 'on',
+             'revision': URLPath.objects.get(slug='deleteme').article.current_revision.id}
+        )
+
+        # Set-up regular user, and login as one.
+        from django.contrib.auth import get_user_model
+        User = get_user_model()
+        regular_user = User.objects.create_user(
+            username='testuser',
+            password='testuser',
+            email='testuser@example.com'
+        )
+
+        if not self.client.login(username='testuser', password='testuser'):
+            raise Exception('Could not login!')
+
+        response = self.client.get(resolve_url('wiki:deleted_list'))
+
+        self.assertRedirects(response, resolve_url('wiki:root'))
+
 
 class MergeViewTest(RequireRootArticleMixin, ArticleWebTestUtils, DjangoClientTestBase):
 
```

**Comment by benjaoming** [comment]
@azaghal can you explain the diff?

**Comment by benjaoming** [comment]
I see the problems @azaghal !

It seems evident that expanding the CustomUser to use a CustomModel has problems with built in permission checks.

I can't see how this would work without also customizing all of the permission checks. This doesn't seems suitable for testing.

```
====================================================================== FAILURES =======================================================================
_______________________________________________ DeletedListViewTest.test_redirect_non_superuser_to_root _______________________________________________

self = <tests.core.test_views.DeletedListViewTest testMethod=test_redirect_non_superuser_to_root>

    def test_redirect_non_superuser_to_root(self):
        response = self.client.post(
            resolve_url('wiki:create', path=''),
            {'title': 'Delete Me', 'slug': 'deleteme', 'content': 'delete me please!'}
        )
    
        response = self.client.post(
            resolve_url('wiki:delete', path='deleteme/'),
            {'confirm': 'on',
             'revision': URLPath.objects.get(slug='deleteme').article.current_revision.id}
        )
    
        # Set-up regular user, and login as one.
        from django.contrib.auth import get_user_model
        User = get_user_model()
        regular_user = User.objects.create_user(
            username='testuser',
            password='testuser',
            email='testuser@example.com'
        )
    
        if not self.client.login(username='testuser', password='testuser'):
            raise Exception('Could not login!')
    
        response = self.client.get(resolve_url('wiki:deleted_list'))
    
>       self.assertRedirects(response, resolve_url('wiki:root'))

tests/core/test_views.py:542: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/test/testcases.py:306: in assertRedirects
    redirect_response = response.client.get(path, QueryDict(query), secure=(scheme == 'https'))
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/test/client.py:517: in get
    response = super().get(path, data=data, secure=secure, **extra)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/test/client.py:332: in get
    return self.generic('GET', path, secure=secure, **r)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/test/client.py:404: in generic
    return self.request(**r)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/test/client.py:485: in request
    raise exc_value
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/core/handlers/exception.py:35: in inner
    response = get_response(request)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/core/handlers/base.py:128: in _get_response
    response = self.process_exception_by_middleware(e, request)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/core/handlers/base.py:126: in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/views/generic/base.py:69: in view
    return self.dispatch(request, *args, **kwargs)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/utils/decorators.py:62: in _wrapper
    return bound_func(*args, **kwargs)
src/wiki/decorators.py:150: in wrapper
    return func(request, article, *args, **kwargs)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/utils/decorators.py:58: in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
src/wiki/views/article.py:38: in dispatch
    return super().dispatch(request, article, *args, **kwargs)
src/wiki/views/mixins.py:26: in dispatch
    user_can_read=request.user):
src/wiki/models/article.py:104: in get_children
    **kwargs).can_read(user_can_read)
src/wiki/managers.py:58: in can_read
    if user.has_perm('wiki.moderate'):
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/contrib/auth/models.py:267: in has_perm
    return _user_has_perm(self, perm, obj)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/contrib/auth/models.py:181: in _user_has_perm
    if backend.has_perm(user, perm, obj):
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/contrib/auth/backends.py:86: in has_perm
    return perm in self.get_all_permissions(user_obj, obj)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/contrib/auth/backends.py:80: in get_all_permissions
    user_obj._perm_cache.update(self.get_group_permissions(user_obj))
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/contrib/auth/backends.py:72: in get_group_permissions
    return self._get_permissions(user_obj, obj, 'group')
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/contrib/auth/backends.py:55: in _get_permissions
    perms = getattr(self, '_get_%s_permissions' % from_name)(user_obj)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/contrib/auth/backends.py:39: in _get_group_permissions
    return Permission.objects.filter(**{user_groups_query: user_obj})
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/db/models/manager.py:82: in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/db/models/query.py:836: in filter
    return self._filter_or_exclude(False, *args, **kwargs)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/db/models/query.py:854: in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/db/models/sql/query.py:1253: in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/db/models/sql/query.py:1277: in _add_q
    split_subq=split_subq,
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/db/models/sql/query.py:1187: in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
.virtualenvs/django-wiki/lib/python3.5/site-packages/django/db/models/sql/query.py:1050: in check_related_objects
    self.check_query_object_type(value, opts, field)
```

**Comment by benjaoming** [comment]
Going to let it fail here for the record, but it can't be implemented, so suggesting that we remove it.

This is btw related to the `AnonymousUser` class having to be changed, because it's also using the default `Group` model.

Just too many things to change.

**Pull request closed without merging**
