### PR TITLE
Isort configuration

### PR DESCRIPTION
**Pull request by rsalmaso**
Move .isort.cfg to config.cfg and expanded to be similar to django one.

### CODE REVIEW

**Comment by benjaoming** [comment]
If you run with the new configuration, does it change stuff in the codebase? Try running it through the pre commit hooks?

**Comment by rsalmaso** [comment]
>If you run with the new configuration, does it change stuff in the codebase?
With this config: yes. see https://gist.github.com/rsalmaso/faf19f430c09836653c5c3a36a4d49a2 for a diff

>Try running it through the pre commit hooks?
I don't know (currently I'm using hg with hg-git), maybe yes. I usually run isort/flake8 manually for reasons.

**Comment by benjaoming** [comment]
> I don't know (currently I'm using hg with hg-git), maybe yes. I usually run isort/flake8 manually for reasons.

That's cool -- the pre-commit hooks are not a policy, the `.travis.yml` linting is the actual policy.

**Comment by benjaoming** [comment]
> With second commit: yes.

This should be part of the PR -- no use leaving it for others to find out :) The changes don't look too bad. Would like to see them pass the tests, otherwise seems good to go.

**Comment by rsalmaso** [comment]
>That's cool -- the pre-commit hooks are not a policy, the .travis.yml linting is the actual policy.

Yes, I run them manually on my machine (they can be really slow sometime) and leave all check when I push.

>This should be part of the PR 

Done

**Comment by benjaoming** [comment]
Diff coverage is not 100% because of the haystack changes, which is fine..

**Pull request merged**
