### PR TITLE
Update to Bootstrap 3.3.1 and Font Awesome 4

### PR DESCRIPTION
**Pull request by cXhristian**
Note: I moved `@fa-font-path` to wiki.less so that the font-awesome directory doesn't contain any changes.

### CODE REVIEW

**Comment by benjaoming** [comment]
This also closes #366

**Comment by benjaoming** [comment]
massive work! I will try it out!

**Comment by benjaoming** [comment]
There seems to be an issue viewing diffs, would you be able to check it out?

screenshot from 2015-01-08 00 41 14

**Comment by benjaoming** [comment]
Apart from that, it looks like the upgrade and refactoring went really well. Big props!!

I think also that *should* there be any glitches, then they are cosmetical, and 0.0.24 is more about bringing a transitional release. So we can get moving!!!

**Comment by benjaoming** [comment]
I'll merge this in around 24h, please add any further changes meanwhile :)

**Comment by cXhristian** [comment]
Diffs seems to be broken on the demo wiki too, so I doubt this was caused by the upgrade. I can take a look at it later today though.

**Comment by cXhristian** [comment]
Ok, I took a look at it. The overflow is caused by one really long line in the diff.
I guess I'll just add an overflow-x: scroll to the diff container. 

Collapse on different diffs seems a bit broken though. I'll fix that. Try opening one diff and then another.

**Comment by cXhristian** [comment]
Everything should be fixed now.

**Pull request merged**
