### PR TITLE
Fix #224

### LINKED ISSUE #224: Initial installation fails with 'django.db.utils.ProgrammingError: relation "notify_subscription" does not exist'
The error is that the migrations for 'wiki' do not depend on the 'django_notify' app.

In particular, you get this error on wiki:0007_auto__add_articlesubscription. It just needs to add:

    depends_on = [("django_notify", "0004")]

### PR DESCRIPTION
**Pull request by the-glu**
As pointed by https://github.com/benjaoming/django-wiki/issues/224#issuecomment-44047813 :)

### CODE REVIEW

**Comment by jessehon** [comment]
Still have the same error on django-1.6.8 and wiki-0.0.24.2

**Comment by benjaoming** [comment]
@jessehon it sounds like you're running into problems with django_nyt vs. django_notify. Have you followed the instructions in the release notes? And are you running a clean installation or an upgrade? Furthermore, please open up a new issue or ask on #django-wiki before posting on the issue tracker, that helps a lot. Thanks.

**Comment by benjaoming** [comment]
@jessehon Tried from a vanilla install, no problems..

**Comment by jessehon** [comment]
@benjaoming Ah sorry about that. I tried with a fresh install and the issue came up with the current stable release - appears the fix were was at some stage. Not a problem in master after the migrations reset though.

**Pull request merged**
