### PR TITLE
Updates to release plan

### PR DESCRIPTION
**Pull request by benjaoming**

### CODE REVIEW

**Review by benjaoming — COMMENTED** [review]
@oscarmcm this was purely cosmetic :) But let's talk about the roadmap any time!

**Comment by oscarmcm** [comment]
@benjaoming so we're only missing a major FE rewrite with bootstrap?

**Comment by benjaoming** [comment]
@oscarmcm I mean, we can put anything in the roadmap - so perhaps it's a good idea to indicate that other releases should be planned as well?

**Comment by oscarmcm** [comment]
I like that idea, I think for 0.12 bootstrap upgrade is a good milestone + any fixes needed from 0.11

**Pull request merged**
