### PR TITLE
Use super instead of calling method on ParentClass

### PR DESCRIPTION
**Pull request by atombrella**
Also deleted a redundant method

### CODE REVIEW

**Comment by benjaoming** [comment]
With the multiple inheritance in these classes, I kind of prefer that the call to a super class is explicit?

**Comment by atombrella** [comment]
Yes, but isn't this simulating that these methods are static, which indeed they aren't in the code-base. I think the codecov-patch is not green because there no tests for those things, and I didn't add any in my patch?

**Comment by benjaoming** [comment]
They are called with `self`, that should make it non-static?

**Comment by atombrella** [comment]
The style looks a bit weird to me, and yes, I did see `self`. I haven't seen in the documentation.

**Comment by atombrella** [comment]
Maybe since there isn't consensus about this change, we should close it.

**Pull request closed without merging**
