### PR TITLE
Added option to disable html sanitizer.

### PR DESCRIPTION
**Pull request by mhozza**

### CODE REVIEW

**Comment by benjaoming** [comment]
Heh, fed up with it? :)

**Comment by benjaoming** [comment]
I would warn that this is pretty unsafe because Markdown has removed `safe_mode` and we're not using that option anymore.

From Markdown docs:

> Both safe_mode and the associated html_replacement_text keywords are deprecated in version 2.6 and will raise a DeprecationWarning. The safe_mode and html_replacement_text keywords will be ignored in version 2.7. The so-called “safe mode” was never actually “safe” which has resulted in many people having a false sense of security when using it. As an alternative, the developers of Python-Markdown recommend that any untrusted content be passed through an HTML sanitizer (like Bleach) after being converted to HTML by markdown.

**Comment by mhozza** [comment]
Actually we had `safe_mode` explicitly disabled. We wanted to be able to add any html to the articles.

**Comment by benjaoming** [comment]
Oh right, well it's going to be released next time, which should be soon... adding it to my TODO now..

**Pull request merged**
