### PR TITLE
Add environments for py3.11 and dj4.1

### PR DESCRIPTION
**Pull request by oscarmcm**
Since support for Python 3.11 was finally added in #1234, this is a continuation of the work and finally have a new version that supports Python 3.11 (#1243, #1232)

### CODE REVIEW

**Comment by oscarmcm** [comment]
It seems that we have an issue in the Circle CI 

```
Starting container circleci/python:3.11
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading circleci/python:3.11

Error response from daemon: manifest for circleci/python:3.11 not found: manifest unknown: manifest unknown
```

**Comment by benjaoming** [comment]
Oh hmm, haven't read about the various flavors of images. Sounds like the `circleci` image isn't being maintained.

Try with `image: cimg/python:<<parameters.python_version>>` instead of `image: circleci/python:<<parameters.python_version>>` ?

**Comment by oscarmcm** [comment]
@benjaoming thanks for the image change proposal 💯 

This is ready to be merged!

**Review by benjaoming — APPROVED** [review]
:rocket:

**Pull request merged**
