### PR TITLE
Adds docker container for test_project

### PR DESCRIPTION
**Pull request by davidzwa**

### CODE REVIEW

**Comment by davidzwa** [comment]
Might improve or move into separate folder!

**Comment by davidzwa** [comment]
Very well, will look into it at a later moment.

**Comment by benjaoming** [comment]
Oh, there is also a potential to add a sentence about it here: https://github.com/django-wiki/django-wiki#docker-tldr

**Comment by benjaoming** [comment]
Hi @davidzwa - I'm not sure if the Dockerfile will contribute much as is. It should possibly be running a later version of Python, and it would need maintenance on its own.

I can understand why people would want to Dockerize the development, though -- yet at the same time, it's possible that they're better off writing their own Dockerfile tailored for their needs?

LMK if this should be reopened, this is not a "no" to Docker.

**Comment by davidzwa** [comment]
It's fine! I shouldve spent more time adjusting the file. I do think dockerizing is nice, but then 100% and not like this partially as I did xD

**Pull request closed without merging**
